### PR TITLE
Added support for .sabermap files (auto-installation)

### PR DESCRIPTION
**Pull request by PiMaker**
The in-game browser is nice and all, but to be honest I prefer searching for songs via the web interface of beatsaver.com. I downloaded a bunch of .zip files and realized that I now had to unpack every single one of them.

So I implemented an auto-extraction feature into your application. Basically, the exe copies itself into the BeatSaber directory and registers itself for the file extension .sabermap (subject to change, was the first good thing that came to mind). That allows simply double-clicking on a zip file that has been renamed with the extension .sabermap to automatically install it into the CustomSongs directory.

If you like the change and accept my pull request, I might also make a PR over on the beatsaver repo to allow downloading of files as .sabermap - That would make installing new maps just a few clicks.

~ Pi

### CODE REVIEW

**Comment by PiMaker** [comment]
Any comments?

**Comment by Umbranoxio** [comment]
Sorry for the late reply, I'll give it a test, and merge, great idea!

**Comment by Byorun** [comment]
Just a quick question: the songs still work even if not extracted. So why not just keep the zips (or .sabermap) and just copy them to the beatsaber customsongs folder?

**Comment by PiMaker** [comment]
Do they? Oh my. Well then, that's a design oversight haha.

**Comment by Byorun** [comment]
@PiMaker sorry for the false information. I never really noticed the .cache folder and after browsing through the songloader code I noticed that if you keep your songs in the zip files the songloader automatically unzips them into the .cache folder. Sorry for my misunderstanding.

**Comment by Gawdl3y** [comment]
You should reopen this - it'd still be much more convenient than the current process.

**Pull request closed without merging**
